### ISSUE TITLE
Upgrade from 13.8.0~ynh1 to 14.0.0~ynh1 fails

### ISSUE THREAD

**Issue by 0utl4w** [YunoHost-Apps/piwigo_ynh#115]
### Describe the bug

Upgrade from 13.8.0~ynh1 to 14.0.0~ynh1 through yunohost web interface fails with "WARNING - parse error: Invalid numeric literal at line 1, column 10"

### Context

- Hardware: VPS bought online (gandi)
- YunoHost version: 11.2.8.2 (stable)
- I have access to my server: Through SSH and through the webadmin
- Using, or trying to install package version/branch:  14.0.0~ynh1
- If upgrading, current package version: 13.8.0~ynh1 

### Expected behavior

Upgrade successfull.

### Logs
https://paste.yunohost.org/raw/ididafitex

**Comment by isAAAc** [comment]
```
root@gourzoot:~# yunohost --version
yunohost: 
  repo: stable
  version: 11.2.9.1
yunohost-admin: 
  repo: stable
  version: 11.2.4
moulinette: 
  repo: stable
  version: 11.2
ssowat: 
  repo: stable
  version: 11.2
```
error here too:   
https://paste.yunohost.org/raw/ziregurata
